
version: '3.8'

services:
  lakehouse-explorer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NESSIE_URI=${NESSIE_URI:-http://nessie:19120/api/v1}
      - S3_ENDPOINT=${S3_ENDPOINT:-http://minio:9000}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-minioadmin}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-minioadmin}
      - WAREHOUSE_PATH=${WAREHOUSE_PATH:-s3://warehouse/}
      - S3_REGION=${S3_REGION:-us-east-1}
      - SSL_VERIFY=${SSL_VERIFY:-false}
    depends_on:
      - nessie
      - minio
    networks:
      - lakehouse

  # Nessie Catalog Service
  nessie:
    image: projectnessie/nessie:latest
    ports:
      - "19120:19120"
    environment:
      - QUARKUS_LOG_LEVEL=INFO
    networks:
      - lakehouse

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lakehouse

networks:
  lakehouse:
    driver: bridge

volumes:
  minio_data:
